### ISSUE TITLE
rule out base 4.18/GHC 9.6 for old versions

### ISSUE THREAD

**Issue by hsenag** [ekmett/transformers-compat#55]
transformers-compat from 0.6.6 to 0.7.1 inclusive don't build with GHC 9.6.1-alpha2

Would you mind amending the bounds on hackage to require base < 4.18?

```
[2 of 4] Compiling Data.Functor.Classes.Generic.Internal ( generics/Data/Functor/Classes/Generic/Internal.hs, /home/ganesh/temp/transformers-compat/transformers-compat-0.6.6/dist-newstyle/build/x86_64-linux/ghc-9.6.0.20230128/transformers-compat-0.6.6/build/Data/Functor/Classes/Generic/Internal.o, /home/ganesh/temp/transformers-compat/transformers-compat-0.6.6/dist-newstyle/build/x86_64-linux/ghc-9.6.0.20230128/transformers-compat-0.6.6/build/Data/Functor/Classes/Generic/Internal.dyn_o )

generics/Data/Functor/Classes/Generic/Internal.hs:819:10: error: [GHC-39999]
    • Could not deduce ‘Eq (FunctorClassesDefault f a)’
        arising from the head of a quantified constraint
        arising from the superclasses of an instance declaration
      from the context: (GEq1 NonV4 (Rep1 f), Generic1 f)
        bound by the instance declaration
        at generics/Data/Functor/Classes/Generic/Internal.hs:819:10-75
      or from: Eq a
        bound by a quantified context
        at generics/Data/Functor/Classes/Generic/Internal.hs:819:10-75
      Possible fix:
        If the constraint looks soluble from a superclass of the instance context,
        read 'Undecidable instances and loopy superclasses' in the user manual
    • In the instance declaration for ‘Eq1 (FunctorClassesDefault f)’
    |
819 | instance (GEq1 NonV4 (Rep1 f), Generic1 f) => Eq1 (FunctorClassesDefault f) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

generics/Data/Functor/Classes/Generic/Internal.hs:821:10: error: [GHC-39999]
    • Could not deduce ‘Ord (FunctorClassesDefault f a)’
        arising from the head of a quantified constraint
        arising from the superclasses of an instance declaration
      from the context: (GOrd1 NonV4 (Rep1 f), Generic1 f)
        bound by the instance declaration
        at generics/Data/Functor/Classes/Generic/Internal.hs:821:10-77
      or from: Ord a
        bound by a quantified context
        at generics/Data/Functor/Classes/Generic/Internal.hs:821:10-77
      Possible fix:
        If the constraint looks soluble from a superclass of the instance context,
        read 'Undecidable instances and loopy superclasses' in the user manual
    • In the instance declaration for ‘Ord1 (FunctorClassesDefault f)’
    |
821 | instance (GOrd1 NonV4 (Rep1 f), Generic1 f) => Ord1 (FunctorClassesDefault f) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

generics/Data/Functor/Classes/Generic/Internal.hs:823:10: error: [GHC-39999]
    • Could not deduce ‘Read (FunctorClassesDefault f a)’
        arising from the head of a quantified constraint
        arising from the superclasses of an instance declaration
      from the context: (GRead1 NonV4 (Rep1 f), Generic1 f)
        bound by the instance declaration
        at generics/Data/Functor/Classes/Generic/Internal.hs:823:10-79
      or from: Read a
        bound by a quantified context
        at generics/Data/Functor/Classes/Generic/Internal.hs:823:10-79
      Possible fix:
        If the constraint looks soluble from a superclass of the instance context,
        read 'Undecidable instances and loopy superclasses' in the user manual
    • In the instance declaration for ‘Read1 (FunctorClassesDefault f)’
    |
823 | instance (GRead1 NonV4 (Rep1 f), Generic1 f) => Read1 (FunctorClassesDefault f) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

generics/Data/Functor/Classes/Generic/Internal.hs:825:10: error: [GHC-39999]
    • Could not deduce ‘Show (FunctorClassesDefault f a)’
        arising from the head of a quantified constraint
        arising from the superclasses of an instance declaration
      from the context: (GShow1 NonV4 (Rep1 f), Generic1 f)
        bound by the instance declaration
        at generics/Data/Functor/Classes/Generic/Internal.hs:825:10-79
      or from: Show a
        bound by a quantified context
        at generics/Data/Functor/Classes/Generic/Internal.hs:825:10-79
      Possible fix:
        If the constraint looks soluble from a superclass of the instance context,
        read 'Undecidable instances and loopy superclasses' in the user manual
    • In the instance declaration for ‘Show1 (FunctorClassesDefault f)’
    |
825 | instance (GShow1 NonV4 (Rep1 f), Generic1 f) => Show1 (FunctorClassesDefault f) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by RyanGlScott** [comment]
Thanks for the heads-up. I've applied the revisions you suggest to each of the affected Hackage releases.
